version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "15:00"
    timezone: Europe/Vienna
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@angular-eslint/builder"
    versions:
    - 2.0.0
    - 2.0.1
    - 2.0.2
    - 2.1.0
    - 4.0.0
    - 4.1.0
  - dependency-name: "@angular-eslint/template-parser"
    versions:
    - 2.0.0
    - 2.0.1
    - 2.0.2
    - 2.1.0
    - 4.0.0
    - 4.1.0
  - dependency-name: "@angular-eslint/eslint-plugin"
    versions:
    - 2.0.0
    - 2.0.1
    - 2.0.2
    - 2.1.0
    - 4.0.0
    - 4.1.0
  - dependency-name: "@angular-eslint/eslint-plugin-template"
    versions:
    - 2.0.0
    - 2.0.1
    - 2.0.2
    - 2.1.0
    - 4.0.0
    - 4.1.0
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.16.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.16.0
  - dependency-name: eslint-config-aqua
    versions:
    - 8.1.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
