module.exports = {
	extends: ['aqua', 'plugin:@typescript-eslint/recommended', 'plugin:promise/recommended'],
	parserOptions: {
		project: './tsconfig.json',
	},
	rules: {
		'@typescript-eslint/adjacent-overload-signatures': 'error',
		'@typescript-eslint/array-type': 0,
		'@typescript-eslint/await-thenable': 0,
		'@typescript-eslint/ban-ts-ignore': 0,
		'brace-style': 0,
		'@typescript-eslint/brace-style': ['error', '1tbs', { allowSingleLine: true }],
		'@typescript-eslint/camelcase': 0,
		'@typescript-eslint/class-name-casing': 'error',
		'@typescript-eslint/consistent-type-definitions': ['error', 'interface'],
		'@typescript-eslint/explicit-function-return-type': 0,
		'@typescript-eslint/explicit-member-accessibility': 'error',
		'func-call-spacing': 0,
		'@typescript-eslint/func-call-spacing': ['error', 'never'],
		indent: 0,
		'@typescript-eslint/indent': ['error', 'tab'],
		'@typescript-eslint/interface-name-prefix': 0,
		'@typescript-eslint/member-delimiter-style': 'error',
		'@typescript-eslint/member-ordering': 0,
		'@typescript-eslint/no-empty-interface': 0,
		'@typescript-eslint/no-explicit-any': 0,
		'@typescript-eslint/no-extraneous-class': 'error',
		'@typescript-eslint/no-for-in-array': 'error',
		'@typescript-eslint/no-misused-new': 'error',
		'@typescript-eslint/no-non-null-assertion': 0,
		'@typescript-eslint/no-require-imports': 'error',
		'@typescript-eslint/no-this-alias': 'error',
		'@typescript-eslint/no-unnecessary-type-arguments': 'error',
		'@typescript-eslint/no-unnecessary-type-assertion': 'error',
		'no-unused-vars': 0,
		'@typescript-eslint/no-unused-vars': [
			'error',
			{
				vars: 'all',
				args: 'after-used',
				ignoreRestSiblings: true,
			},
		],
		'@typescript-eslint/no-useless-constructor': 'error',
		'@typescript-eslint/no-var-requires': 'error',
		'@typescript-eslint/prefer-for-of': 'error',
		'@typescript-eslint/prefer-includes': 'error',
		'@typescript-eslint/prefer-readonly': 'error',
		'@typescript-eslint/prefer-regexp-exec': 'error',
		'@typescript-eslint/promise-function-async': 0,
		quotes: 'off',
		'@typescript-eslint/quotes': ['error', 'single', { avoidEscape: true, allowTemplateLiterals: true }],
		'@typescript-eslint/restrict-plus-operands': 'error',
		semi: 0,
		'@typescript-eslint/semi': 'error',
		'@typescript-eslint/type-annotation-spacing': 'error',
		'@typescript-eslint/unified-signatures': 'error',
		'no-dupe-class-members': 0,
		'promise/catch-or-return': 'error',
		'promise/no-return-wrap': 'error',
		'promise/param-names': 'error',
		'promise/always-return': 'error',
		'promise/no-nesting': 'error',
		'promise/no-new-statics': 'error',
		'promise/prefer-await-to-then': 'error',
		'promise/prefer-await-to-callbacks': 'error',
	},
};
