module.exports = {
	extends: ['aqua', 'plugin:@typescript-eslint/recommended', 'plugin:promise/recommended'],
	parserOptions: {
		project: './tsconfig.json',
	},
	rules: {
		'@typescript-eslint/adjacent-overload-signatures': 1,
		'@typescript-eslint/array-type': 0,
		'@typescript-eslint/await-thenable': 0,
		'@typescript-eslint/ban-ts-ignore': 0,
		'brace-style': 0,
		'@typescript-eslint/brace-style': [1, '1tbs', { allowSingleLine: true }],
		'@typescript-eslint/camelcase': 0,
		'@typescript-eslint/class-name-casing': 1,
		'@typescript-eslint/consistent-type-definitions': [1, 'interface'],
		'@typescript-eslint/explicit-function-return-type': 0,
		'@typescript-eslint/explicit-member-accessibility': 1,
		'func-call-spacing': 0,
		'@typescript-eslint/func-call-spacing': [1, 'never'],
		indent: 0,
		'@typescript-eslint/indent': [1, 'tab'],
		'@typescript-eslint/interface-name-prefix': 0,
		'@typescript-eslint/member-delimiter-style': 1,
		'@typescript-eslint/member-ordering': 0,
		'@typescript-eslint/no-empty-interface': 0,
		'@typescript-eslint/no-explicit-any': 0,
		'@typescript-eslint/no-extraneous-class': 1,
		'@typescript-eslint/no-for-in-array': 1,
		'@typescript-eslint/no-misused-new': 1,
		'@typescript-eslint/no-non-null-assertion': 0,
		'@typescript-eslint/no-require-imports': 1,
		'@typescript-eslint/no-this-alias': 1,
		'@typescript-eslint/no-unnecessary-type-arguments': 1,
		'@typescript-eslint/no-unnecessary-type-assertion': 1,
		'no-unused-vars': 0,
		'@typescript-eslint/no-unused-vars': [
			1,
			{
				vars: 'all',
				args: 'after-used',
				ignoreRestSiblings: true,
			},
		],
		'@typescript-eslint/no-useless-constructor': 1,
		'@typescript-eslint/no-var-requires': 1,
		'@typescript-eslint/prefer-for-of': 1,
		'@typescript-eslint/prefer-includes': 1,
		'@typescript-eslint/prefer-readonly': 1,
		'@typescript-eslint/prefer-regexp-exec': 1,
		'@typescript-eslint/promise-function-async': 0,
		quotes: 0,
		'@typescript-eslint/quotes': [1, 'single', { avoidEscape: true, allowTemplateLiterals: true }],
		'@typescript-eslint/restrict-plus-operands': 1,
		semi: 0,
		'@typescript-eslint/semi': 1,
		'@typescript-eslint/type-annotation-spacing': 1,
		'@typescript-eslint/unified-signatures': 1,
		'no-dupe-class-members': 0,
		'no-undef': 0,
		'promise/catch-or-return': 1,
		'promise/no-return-wrap': 1,
		'promise/param-names': 1,
		'promise/always-return': 1,
		'promise/no-nesting': 1,
		'promise/no-new-statics': 1,
		'promise/prefer-await-to-then': 1,
		'promise/prefer-await-to-callbacks': 1,
	},
};
